- name: Get windows password from instance
  ec2_win_password:
    region: "{{ region }}"
    instance_id: "{{ instance_id }}"
    key_file: "{{ key_path }}"
    wait: yes
    wait_timeout: 300
  register: win_password
